### ISSUE TITLE
Sibling of the leaf to be remembered should not be counted as computable

### ISSUE THREAD

**Issue by kcalvinalvin** [mit-dci/libutreexo#10]
https://github.com/mit-dci/libutreexo/blob/375b2d85bd11bf86a5047c7ddc61537e8af42db6/src/state.h#L83

`ProofPositions()` will return the sibling of the node to be cached as a computable node.

For example:

```
std::vector<Leaf> leaves;
CreateTestLeaves(leaves, 8);

leaves[1].second = true;
```

Will create a tree like so (* means the leaf needs to be cached):

```
14
|---------------\
12              13
|-------\       |-------\
08      09      10      11
|---\   |---\   |---\   |---\
00  01* 02  03  04  05  06  07
```

`00` must also be cached in order to prove `01` and is not computable. However:

```
auto positions = current_state.ProofPositions(std::vector<uint64_t>{0})
```

will output

```
positions: [1, 9, 13]
computable: [0, 8, 12, 14]
```

**Comment by dergoegge** [comment]
`computable` is the set of target positions and position of nodes in the forest that get computed during verification.

`current_state.ProofPositions(std::vector<uint64_t>{0})` <- "give me the positions for target 0"

`ForestState` is not aware of any cached nodes, it simply provides a wrapper around the number of leaves and implements position utilities.

**Comment by kcalvinalvin** [comment]
Nevermind the code is correct. The code 

```
auto positions = current_state.ProofPositions(std::vector<uint64_t>{0})
```

should've been passing in `1` instead of `0`
